- name: Deinstall False or old docker packages
  apt: "name={{item}} state=absent"
  with_items:
  - docker
  - docker-engine
  - docker.io

- name: Save Release > 'lsb_release'
  shell: echo $(lsb_release -cs)
  register: lsb

- name: Install Docker Requirements
  apt: state=present name={{ item }} update_cache=yes cache_valid_time=3600 autoremove=true
  with_items: ubuntu_pkg
  environment: env

- name: Add Apt Signing Key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    keyring: /etc/apt/trusted.gpg.d/docker.gpg

- name: Add Apt Repository
  apt_repository: 
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{lsb.stdout}} stable"
    state: present
    filename: docker

- name: Install Docker
  apt: state=present name={{ item }} update_cache=yes cache_valid_time=3600 autoremove=true
  with_items: 
    - docker-ce
